# Generated by Django 3.1.7 on 2021-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelocation',
            name='city',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='country',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='driving_directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='gps_coords',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='phone_num',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='postal',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='region',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='short_name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='street_address',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
