# Generated by Django 3.1.7 on 2021-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_auto_20210430_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category_id', models.BigIntegerField()),
                ('version_id', models.BigIntegerField(blank=True)),
                ('is_disabled', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
