# Generated by Django 3.1.7 on 2021-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_resourcecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_category_id', models.IntegerField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
