# Generated by Django 3.1.7 on 2021-05-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0004_auto_20210501_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_definition_id', models.IntegerField()),
                ('main_name', models.CharField(blank=True, max_length=48, null=True)),
                ('version_id', models.BigIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('min_value', models.BigIntegerField(default=None, null=True)),
                ('max_value', models.BigIntegerField(default=None, null=True)),
                ('subclass_name', models.CharField(default=None, max_length=48, null=True)),
                ('subclass_enum', models.IntegerField(default=None, null=True)),
                ('subclass_order', models.IntegerField(default=None, null=True)),
                ('subclass_is_active', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
