# Generated by Django 3.1.7 on 2021-05-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category_id', models.IntegerField()),
                ('version_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
