# Generated by Django 3.1.7 on 2021-05-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0006_feecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rootmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('resource_categories', models.ManyToManyField(blank=True, related_name='rootmap', to='camping.ResourceCategory')),
                ('resource_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rootmap', to='camping.resourcelocation')),
            ],
        ),
    ]
