# Generated by Django 3.1.7 on 2021-05-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0007_rootmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.BigIntegerField()),
                ('version_id', models.BigIntegerField()),
                ('version_date', models.CharField(blank=True, max_length=48, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('date_schedule_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('max_stay', models.IntegerField(blank=True, null=True)),
                ('min_capacity', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('allowed_equipment', models.ManyToManyField(blank=True, related_name='site', to='camping.Equipment')),
                ('fee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='camping.feecategory')),
                ('resource_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='camping.resourcecategory')),
                ('resource_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='camping.resourcelocation')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=24, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_attributes', to='camping.attribute')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_attributes', to='camping.site')),
            ],
        ),
    ]
