# Generated by Django 3.1.7 on 2021-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0008_site_siteattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='version_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InUseOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(blank=True, related_name='inUseOptions', to='camping.Attribute')),
                ('equipment', models.ManyToManyField(blank=True, related_name='inUseOptions', to='camping.Equipment')),
                ('resource_categories', models.ManyToManyField(blank=True, related_name='inUseOptions', to='camping.ResourceCategory')),
                ('resource_locations', models.ManyToManyField(blank=True, related_name='inUseOptions', to='camping.ResourceLocation')),
            ],
        ),
    ]
