# Generated by Django 3.1.7 on 2021-05-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0009_auto_20210503_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='inuseoptions',
            name='name',
            field=models.CharField(default='everything', max_length=24),
            preserve_default=False,
        ),
    ]
