# Generated by Django 3.1.7 on 2021-05-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0010_inuseoptions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.BigIntegerField()),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_image_uid', models.CharField(blank=True, max_length=48, null=True)),
                ('rootmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_map', to='camping.rootmap')),
                ('sites', models.ManyToManyField(related_name='camp_map', to='camping.Site')),
            ],
        ),
    ]
