# Generated by Django 3.1.7 on 2021-05-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0011_campgroundmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgroundmap',
            name='resource_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_map', to='camping.resourcelocation'),
        ),
    ]
