# Generated by Django 3.2.9 on 2021-11-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='contact',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='priority',
            new_name='rank',
        ),
    ]
