# Generated by Django 3.2.9 on 2021-11-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_cell',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_office',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries', to='cellar.Contact'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cellar.customer'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
