# Generated by Django 3.2.9 on 2021-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0005_auto_20211111_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Toronto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Canada', max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='L3P 3A2', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='Ontario', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_addr_1',
            field=models.CharField(default='125 Redpath Ave', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_addr_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
