# Generated by Django 3.2.9 on 2021-11-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0007_tag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
