# Generated by Django 3.2.9 on 2021-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0008_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
