# Generated by Django 3.2.9 on 2021-12-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0014_auto_20211216_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_edited',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
