# Generated by Django 3.2.9 on 2021-12-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0016_auto_20211229_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='cellar.entry'),
        ),
    ]
