# Generated by Django 3.2.9 on 2021-12-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0017_auto_20211229_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cellar.entry'),
        ),
    ]
