# Generated by Django 3.2.9 on 2022-01-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0018_alter_photo_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dollar_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='likelihood',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
