# Generated by Django 3.2.9 on 2022-01-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0019_auto_20220102_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_archived',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_flagged',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
